# Generated by Django 6.0.7 on 2026-07-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified_user_otp_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
