# Generated by Django 6.0.7 on 2026-07-28 15:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to='budgets.budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='categories.category')),
            ],
            options={
                'db_table': 'category_budgets',
            },
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'month', 'year'), name='unique_active_budget_per_month'),
        ),
        migrations.AddConstraint(
            model_name='categorybudget',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('budget', 'category'), name='unique_active_category_budget'),
        ),
    ]
