# Generated by Django 6.0.7 on 2026-07-28 14:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='EXPENSE', max_length=10)),
                ('icon', models.CharField(blank=True, default='tag', max_length=50)),
                ('color', models.CharField(blank=True, default='#6B7280', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Leave blank for system-wide categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['user', 'category_type'], name='categories_user_id_4bbd72_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'name', 'category_type'), name='unique_user_category_type')],
            },
        ),
    ]
