# Generated by Django 6.0.7 on 2026-07-31 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='next_recurrence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The original expense this was generated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_children', to='expenses.expense'),
        ),
    ]
